### ISSUE TITLE
Corrupted bundle when including babel-polyfill

### ISSUE THREAD

**Issue by feugy** [choojs/bankai#362] opened 2018-01-02 15:23 UTC
Hello!

I've spot a very tricky situation when including the babel-polyfill and building with bankai.
There's a repository [here](https://github.com/feugy/tinyify-pack-flat) to reproduce the error.

During the build phase, bankai is applying tinyify transformation that minifies code, but also removes the function wrappers around each module. 
When babel-polyfill is added, it creates several variable conflicts between modules, and the generated bundle becomes unusable.

This doesn't happen when:
- using `bankai start` command
- using bundle-collapser plugin instead of browser-pack-flat plugin, which requires to set [`flat` option to `false`](https://github.com/browserify/tinyify/blob/master/index.js#L31).
As bankai doesn't allow to set this option, it must be changed manually in node_modules

**Comment by goto-bus-stop** [comment] 2018-01-02 16:31
ohh i see, browser-pack-flat is not renaming the `Math` variable defined in one of core-js's modules. a quick fix would be to add knowledge of global browser variables to browser-pack-flat. a better one would be to keep track of all undefined variables used by each module and assume all of them are globals. i'll check out if the latter is doable and otherwise add the former for now

**Comment by goto-bus-stop** [comment] 2018-01-02 21:22
hey, this should be fixed in browser-pack-flat v3.0.6--variable names that are used in a module but not declared are assumed to be global variables that should not be touched. could you check if that fixes it for you? an `npm update` should upgrade to the new version. thanks!

**Comment by feugy** [comment] 2018-01-02 21:37
@goto-bus-stop thanks for the quick answer!

Yes, installing version 3.0.6 fix it. 
This is wonderful: it took me more than a day to troubleshoot this blocking issue (to me at least).

But I don't understand why the latest version didn't came by itself: you used loose versioning in your [package.json](https://github.com/browserify/tinyify/blob/master/package.json#L10).

Is it because of `package-lock.json`?

**Comment by goto-bus-stop** [comment] 2018-01-02 21:42
yeah sorry, tinyify is a pain to debug--bundle flattening + uglify doesn't make for an easy to read result :( thanks for taking the time to pinpoint browser-pack-flat, luckily the problem was reproducible with _only_ browser-pack-flat and no minification 😆 

yeah, my understanding is that when using `npm install` when a package-lock.json is present, it doesn't update (nested) dependencies anymore. you have to explicitly `npm update` in order to get new versions.

**Comment by goto-bus-stop** [comment] 2018-01-03 17:10
assuming this is resolved then :) thanks!

**Closed by goto-bus-stop** 2018-01-03 17:10 UTC
