### ISSUE TITLE
v9.2.0 not loading static assets

### ISSUE THREAD

**Issue by gavinpatkinson** [choojs/bankai#382] opened 2018-01-16 22:53 UTC
I updated bankai but it no longer loads static assets from ./assets. Without changing anything but the version no assets are loaded.

**Comment by yoshuawuyts** [comment] 2018-01-17 22:34
@gavinpatkinson oh, that's bizarre. Shouldn't be happening! Are you seeing any errors anywhere?

**Comment by gavinpatkinson** [comment] 2018-01-17 22:42
No error, bankai bundles and serves. No error in console either.  I was wondering if the src path that the app expects has changed – right now I'm using something like `const imageURL = 'assets/images/' + project.filename`

**Comment by yoshuawuyts** [comment] 2018-01-18 00:48
@gavinpatkinson I'm having trouble reproducing this, https://github.com/yoshuawuyts/repro-bankai-382/blob/master/index.js#L18-L27 seems to be working as expected.

```js
app.use((state, emitter) => {
  window.fetch('/assets/icon.png')
    .then((res) => {
      console.log('ok', res.ok)
      console.log(res)
    })
    .catch((err) => {
      emitter.emit('log:error', err)
    })
})
```

![2018-01-18-014336_1920x1080](https://user-images.githubusercontent.com/2467194/35075052-655a765c-fbf1-11e7-9fbb-6ef8f313f535.png)


Could you perhaps try cloning https://github.com/yoshuawuyts/repro-bankai-382, and give it a shot. If you find a failure scenario, a PR to the repo might be useful.

Thanks, and sorry this is being a bit of a pain to track down. I'm confident we'll be able to get to the bottom of it tho! Thanks for your patience :grin:

**Comment by greggraf** [comment] 2018-01-18 23:18
I have observed a similar change in behavior. 

Whether it is an appropriate use of the `/assets/` directory or not, previously I was able to get `/assets/file.json` to serve from there.  

I am able to reproduce the use case @gavinpatkinson has (image files in a subdirectory of `/assets/` ie: `/assets/images/image.jpg`) and it seems to be failing for a similar reason. 

In https://github.com/choojs/bankai/commit/79d2aad6b9a135f972265e6edf9019524800aa49 there are some RegExs that change previous behavior.

The one for assets is affecting @gavinpatkinson.

Previous RegEx behavior for assets:
```
> '/assets/image.png'.search(/^\/assets\/(.*)$/)
< 0
> '/assets/images/image.jpg'.search(/^\/assets\/(.*)$/)
< 0
```
Current RegEx behavior for assets:
```
> '/assets/image.png'.search(/^\/assets\/([a-zA-Z0-9-_.]*)\?{0,1}[\w&=]*$/)
< 0
> '/assets/images/image.jpg'.search(/^\/assets\/([a-zA-Z0-9-_.]*)\?{0,1}[\w&=]*$/)
< -1
```

For me, files ending in `.json` are now getting treated like `.js` files and fall into the bundler logic, never getting to the asset logic.

Previous RegEx behavior for js files:
```
> '/assets/file.js'.search(/\/([a-zA-Z0-9-_]+)\.js$/)
< 7
> '/assets/file.json'.search(/\/([a-zA-Z0-9-_]+)\.js$/)
< -1
```
Current RegEx behavior for js files:
```
> '/assets/file.js'.search(/\/([a-zA-Z0-9-_.]+)\.js\?{0,1}[\w&=]*$/)
< 7
> '/assets/file.json'.search(/\/([a-zA-Z0-9-_.]+)\.js\?{0,1}[\w&=]*$/)
< 7
```

I this makes sense, I can  update the test file with these use cases and submit a branch with an updated RegEx

**Comment by yoshuawuyts** [comment] 2018-01-19 21:12
@greggraf ohhhh, right - I see. Yeah a branch for this would be grand!

**Comment by gavinpatkinson** [comment] 2018-01-20 19:30
Thank you all!

**Comment by goto-bus-stop** [comment] 2018-04-06 10:15
#396 was merged so I assuuuuume this is solved. thanks!

**Closed by goto-bus-stop** 2018-04-06 10:15 UTC
