### ISSUE TITLE
Bug with babelify (or the user)

### ISSUE THREAD

**Issue by danielepolencic** [choojs/bankai#208] opened 2017-06-30 22:31 UTC
Hi,

I want to compile the following two files:

## A.js

```js
import * as B from './b';
```

## B.js

```js
console.log('Hello');
```

I used the following command:

```shell
bankai a.js -j [ -t babelify ] -H
```

I get the following error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing file: /Users/pole/Sites/pacman-mcts/a.js
    at Parser.pp$4.raise (/Users/pole/Sites/pacman-mcts/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:2549:13)
    at Parser.pp$1.parseStatement (/Users/pole/Sites/pacman-mcts/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:775:14)
    at Parser.pp$1.parseTopLevel (/Users/pole/Sites/pacman-mcts/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:684:23)
    at Parser.parse (/Users/pole/Sites/pacman-mcts/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:541:15)
    at parse (/Users/pole/Sites/pacman-mcts/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:3549:37)
    at module.exports (/Users/pole/Sites/pacman-mcts/node_modules/yo-yoify/node_modules/falafel/index.js:22:15)
    at DestroyableTransform.end [as _flush] (/Users/pole/Sites/pacman-mcts/node_modules/yo-yoify/index.js:56:13)
    at DestroyableTransform.<anonymous> (/Users/pole/Sites/pacman-mcts/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:86:13)
error Command failed with exit code 1.
```

I had a feeling that error may be related to how the transforms are ingested. So I hacked the code and added the following line: `b.transform('babelify')` here: https://github.com/yoshuawuyts/bankai/blob/5c3502f7c6955f23b3d78a7f1ae383a81da299ef/index.js#L88 and it worked.

From what I can tell, the babelify transform is not picked up OR the order is incorrect.

Is this a bug or am I missing something?

Notes:

```
$(yarn bin)/bankai -v
8.1.1

node -v
v6.9.4

$(yarn bin)/browserify --version
14.3.0
```

**Comment by louiscenter** [comment] 2017-07-02 11:00
@danielepolencic - someone pointed out to me recently on `#choo` that I needed to use `--transform` instead of `-t` when configuring `browserify` via `bankai` on the command line.

Does this help at all?

**Comment by yoshuawuyts** [comment] 2017-07-02 22:14
Lmao, we should totally fix that btw

**Comment by millette** [comment] 2017-11-23 02:26
Duplicate of #115

**Closed** 2017-12-24 18:46 UTC
